### ISSUE TITLE
very large numbers are crashing the app

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#107]
App needs to be more intelligent when moving from BNs to vanilla numbers.

![bn js issue](https://user-images.githubusercontent.com/13929023/172217128-c01fb604-23e6-43b8-ba1e-71e72218b839.png)

**Comment by hamidra** [comment]
I was making some changes regarding this. 
I believe we need to make all numbers BN and only convert when we display.
I'll send a PR to see if it makes sense to have sth like that.
