### ISSUE TITLE
View nominator account info without connect wallet

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-staking-dashboard#115]
So people can track Karura / Acala parachain nominator account performance.

BTW the feedback page isn't working for me. I tried login with Github and Google and getting errors when posting message there.

**Comment by rossbulat** [comment]
Can you give more details on how nominators work on Acala? Acala is like a multi-chain Maker DAO, I am not sure if we are considering nominators to be the same thing as Polkadot nominators here.

There will be a few milestones to be reached before supporting a multi-chain supported staking dashboard. The first major milestone will be migrating from Polkadot JS API to a [Chain API](https://github.com/paritytech/capi) integration, that will enable this sort of functionality.

Beyond this the dashboard will need to become more modular, supporting the varying pallets / types of staking and such. 

Nevertheless, definitely something to work towards @harrysolovay.

**Comment by xlc** [comment]
No I think you misunderstood my request. There isn't really any multi chain component involved. 

This is a sub account controlled by Acala parachain sovereign account on Polkadot and it is perform staking on behalf of all LDOT holders: https://polkadot.subscan.io/account/15sr8Dvq3AT3Z2Z1y8FnQ4VipekAHhmQnrkgzegUr1tNgbcn

So all I am asking is simply allow me to enter this address, and view related stats.

**Comment by rossbulat** [comment]
Got it, thank you for expanding. 

Agreed, this would be very useful and worthwhile implementing.

**Comment by rossbulat** [comment]
Hi @xlc, I just merged a read-only account feature. I can now import `15sr8Dvq3AT3Z2Z1y8FnQ4VipekAHhmQnrkgzegUr1tNgbcn` and see its staking status. Is this what you were after?:

<img width="1756" alt="Screenshot 2022-06-21 at 12 06 37" src="https://user-images.githubusercontent.com/13929023/174786696-be132867-aa0b-4dc1-9ba0-cb16b094ddb3.png">

**Comment by xlc** [comment]
Thanks. That's exactly what I want.
