### ISSUE TITLE
👷‍♂️ No styled components based dependencies

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#1160]
Styled components now picks up if there are multiple instances instantiated in your app as a result of dependencies having different versions of the package installed. 

Since we do not have control of every dependency in staking dashboard, the only real viable solution to prevent this is **to not use styled components in any of our dependencies.**

We have began this trend with `@polkadotcloud/core-ui`, that compiles SCSS into a minified CSS file. If every dependency relies on plain CSS, we can bundle all CSS and or split it into chunks to further optimise the app size.

### TODO

- [x] Identify which dependencies use styled components.
`@polkadot/react-qr` and `@polkadot/react-identicon`.
- [x] Replace or amend dependencies that use styled components.

**Comment by TingALin** [comment]
@polkadot/react-qr and @polkadot/react-identicon for now
