### ISSUE TITLE
ChangeNomination component should let to add new nominations.

### ISSUE THREAD

**Issue by hamidra** [paritytech/polkadot-staking-dashboard#117]
Currently the change nomination component only let to stop/remove some nominations.
The work around in the staking page is to stop the current nominations first and then start new nominations from favorites or most profitable choices.
However, this work around is not possible for pools since an active pool can not stop nominations once it has started staking/nominating.

I suggest we either let the nominator add some nominations in the ChangeNominations component,
Or let them switch back and forth between new/reset nominations and stop nominations in that component.
under the hood, technically there is no stop nominations and there is only one extrinsic that sets the nomination possible (stop in staking sets the nomination set to empty.), so these are only handled in UX, so the UX can be smart and let the nominator swap, remove or add nominations

**Comment by rossbulat** [comment]
We now have an "Add From Favourites" button that opens a modal to select from them. We can submit the extrinsic directly in the modal:

<img width="1498" alt="Screenshot 2022-06-18 at 12 04 34" src="https://user-images.githubusercontent.com/13929023/174434925-112f3ca0-1d18-469f-b6db-63b5ef4b32d4.png">

<img width="1434" alt="Screenshot 2022-06-18 at 12 04 26" src="https://user-images.githubusercontent.com/13929023/174434928-6794864f-6c80-41fc-9417-45604f350876.png">
