### ISSUE TITLE
Add status icons for the pool.

### ISSUE THREAD

**Issue by hamidra** [paritytech/polkadot-staking-dashboard#123]
Currently, if the pool is locked or is destroying the status is not obvious in the pool status card.
We need to add proper icons to show the current status of the pool (locked, destroying, ...)
Also when the pool is destroying the lock / unlock icon could be replaced with a destroying icon.

**Comment by rossbulat** [comment]
I have amended the Pool Status to show additional icons and text when a pool is locked or destroying:

<img width="784" alt="Screenshot 2022-06-18 at 12 02 21" src="https://user-images.githubusercontent.com/13929023/174434867-71be6a7b-7524-43ce-8e39-2d417bd29fe9.png">
