### ISSUE TITLE
App crashes when connecting a wallet - Firefox

### ISSUE THREAD

**Issue by Tbaut** [paritytech/polkadot-staking-dashboard#125]
It crashes when I try to connect, from https://paritytech.github.io/polkadot-staking-dashboard/#/overview with the error
> Uncaught TypeError: t is null

I have nothing unusual, just the pjs extension with accounts, `paritytech.github.io` is allowed in the extension.

Screencast how it happens

https://user-images.githubusercontent.com/33178835/173942855-af4a021b-4882-49bd-8f0a-db85a7181c12.mp4

The console
![image](https://user-images.githubusercontent.com/33178835/173942510-d90c2724-b1ea-4b34-917f-f8dfb8e71759.png)

it points to the following line
```js
export const clipAddress = (val: string) => {
  return `${val.substring(0, 6)}...${val.substring( // <----------- pointing here
    val.length - 6,
    val.length
  )}`;
};
```

**Comment by rossbulat** [comment]
Thank you for identifying @Tbaut, will investigate in more detail shortly.

**Comment by rossbulat** [comment]
I just tested on a clean install of Firefox and cannot reproduce the issue. Is it still happening if you clear all your cookies and site data?

**Comment by Tbaut** [comment]
I tried in a private window and the same happens.
Digging a bit, I logged the props here: https://github.com/paritytech/polkadot-staking-dashboard/blob/master/src/modals/ConnectAccounts/Account.tsx#L62

and figured that some are null
```
props 
Object { address: null, meta: null, label: (2) […], asElement: true }
```

Which shows some inconsistencies in what is done before. Sorry I didn't take the time to look more. Having a basic `if (!address) return null` let the app work.

Did you play with accounts coming from Signer, or derived accounts?

**Comment by rossbulat** [comment]
Thanks for digging deeper. I've amended that component and deployed an unmerged branch. Please let me know if the issue is still persisting!

**Comment by Tbaut** [comment]
it's working well now yes.
I'm seeing a stash "Not imported" as the first line, I'm not sure if that's linked or not.
![image](https://user-images.githubusercontent.com/33178835/174188992-05511bfb-ba93-4cd7-af10-04f7dc99bf01.png)

In any case it's solved.
