### ISSUE TITLE
Add support for more Networks

### ISSUE THREAD

**Issue by jamesbayly** [paritytech/polkadot-staking-dashboard#126]
Hey, SubQuery is working with Nova Wallet to build an open source and public staking data source for each and every parachain. It will be a standardized GraphQL endpoint. 

Can we talk about getting this into your new staking dashboard as a service endpoint or adding the additional networks? 

Please reach out to me on Telegram under @jamesbayly

**Comment by rossbulat** [comment]
Hi James, yes this sounds exciting. What sorts of endpoints can you foresee being beneficial to the dashboard? We are interested in supporting validators a lot more, and already have a few ideas on how to do that. We should explore whether SubQuery can provide an additional layer of useful metrics.

**Comment by jamesbayly** [comment]
@rossbulat  are you in Berlin next week for Decoded? if so, lets discuss in person otherwise please find some time with me https://calendly.com/jamesbayly/30min

**Comment by rossbulat** [comment]
> @rossbulat  are you in Berlin next week for Decoded? if so, lets discuss in person otherwise please find some time with me https://calendly.com/jamesbayly/30min

I will indeed, I'll be speaking on the 30th and will be around both days.

**Comment by jamesbayly** [comment]
Hey @rossbulat, it looks like I missed you there. Would you be able to book some time with me here https://calendly.com/jamesbayly/30min
