### ISSUE TITLE
Add Integration of SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [paritytech/polkadot-staking-dashboard#130]
Dear @rossbulat 

This is Ryan from SubWallet. Please also integrate SubWallet into the staking dashboard to bring a better experience for users.
We have created a mini-app for integration and here is the detailed instruction:
- https://docs.subwallet.app/integration/integration-instructions

Thank you very much and really looking forward to it.
For any questions, please reach out to me on Element: @ryandinh8:matrix.org

Cheers,
Ryan.

**Comment by rossbulat** [comment]
I will work to get this integrated by the end of the month. Supporting a range of extensions & ways to connect wallets should be a top priority beyond MVP. Thank you for your work on the SubWallet API and supporting the entire ecosystem of wallets.

**Comment by RyanDinh8** [comment]
Thank you very much. We are all looking forward to that. SubWallet is trying to do everything to bring better UI/UX for users in the entire ecosystem.

**Comment by hieudd** [comment]
> I will work to get this integrated by the end of the month. Supporting a range of extensions & ways to connect wallets should be a top priority beyond MVP. Thank you for your work on the SubWallet API and supporting the entire ecosystem of wallets.

Hi @rossbulat, I saw Polkadot announce this Dashboard but still do not see SubWallet integrated, do you need our help?

**Comment by rossbulat** [comment]
I'm working on a PR now, getting there:

<img width="856" alt="Screenshot 2022-07-08 at 11 31 52" src="https://user-images.githubusercontent.com/13929023/177975804-1b1e3658-ee3d-49dc-8c3f-ae10f91b7269.png">

**Comment by rossbulat** [comment]
On a separate note, but I am getting this console error when I have the SubWallet extension enabled:

<img width="313" alt="Screenshot 2022-07-08 at 11 39 26" src="https://user-images.githubusercontent.com/13929023/177976979-49ac4804-c298-474f-a850-7b0eaf68e8cf.png">

**Comment by rossbulat** [comment]
I've merged the PR. SubWallet is now supported in the codebase.
I am going to spend a bit of time using the project locally before pushing to production to ensure there are no bugs. I've abstracted extensions into a config file so extension teams can submit a PR with their own extension added. We are not solely relying on `web3injected`, so some refactoring to test-drive.

Will push to production shortly, no later than the weekend!

**Comment by hieudd** [comment]
> I'm working on a PR now, getting there:
> 
> <img alt="Screenshot 2022-07-08 at 11 31 52" width="856" src="https://user-images.githubusercontent.com/13929023/177975804-1b1e3658-ee3d-49dc-8c3f-ae10f91b7269.png">

> I've merged the PR. SubWallet is now supported in the codebase. I am going to spend a bit of time using the project locally before pushing to production to ensure there are no bugs. I've abstracted extensions into a config file so extension teams can submit a PR with their own extension added. We are now solely relying on `web3injected` rather than `talisman-connect`, so there is some refactoring to test-drive.
> 
> Will push to production shortly, no later than the weekend!

Thank you so much for the quick implementation.


> On a separate note, but I am getting this console error when I have the SubWallet extension enabled:
> 
> <img alt="Screenshot 2022-07-08 at 11 39 26" width="313" src="https://user-images.githubusercontent.com/13929023/177976979-49ac4804-c298-474f-a850-7b0eaf68e8cf.png">

We will test it again and fix it in an upcoming release. Thank you so much!
