### ISSUE TITLE
Object.hasOwn not supported on Safari 15.2

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-staking-dashboard#133]
<img width="970" alt="Screen Shot 2022-06-22 at 11 15 04 AM" src="https://user-images.githubusercontent.com/1201310/174911808-443190d0-ecec-44ef-9313-87601c762e03.png">

https://caniuse.com/?search=hasown

I am still using Safari 15.2 which doesn't support `Object.hasOwn`

**Comment by rossbulat** [comment]
Thank you for identifying. I will fix shortly.
