### ISSUE TITLE
Account List: Sort nominations by status

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-staking-dashboard#134]
Should sort nominations by status. Maybe add buttons to change sorting criteria like name, commissions etc.

---

<img width="848" alt="Screen Shot 2022-06-22 at 11 28 25 AM" src="https://user-images.githubusercontent.com/1201310/174912991-dee1619f-3d19-4373-861c-2ca96b674313.png">

It is not obvious that I need to click Extensions to manage accounts. Maybe just call it accounts.

**Comment by rossbulat** [comment]
Thanks for the feedback! I will work through (please allow me to edit your post and remove some content as and when I fix them).
