### ISSUE TITLE
Add CI/CD GitLab Runners

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#141]
Automated checks need to be introduced for PRs to ensure code integrity and to make the review process easier.

Checks to be introduced:
- [x] `yarn lint` and check for errors
- [ ] ensure head comment w. copyright info is present on all eligible files
- [x] ensure `yarn build` succeeds
- [x] ensure `yarn test` succeeds

These checks are in addition to the 1 review that is already required for merging PRs.

**Comment by wirednkod** [comment]
Why Gitlab?

**Comment by rossbulat** [comment]
It was just the platform in my head while I was writing the issue. No strict requirement to use one solution over another for now.
