### ISSUE TITLE
Translations needed for claim payout modal

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#1416]
The content in `src/modals/ClaimPayout/` needs to be translated into Chinese.

@TingALin would you be able to assist?

<img width="709" alt="Screenshot 2023-09-11 at 12 33 00" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/13929023/8f131eeb-d9bf-4912-8e94-6911fa514229">

**Comment by ASISBusiness** [comment]
> The content in `src/modals/ClaimPayout/` needs to be translated into Chinese.
> 
> @TingALin would you be able to assist?
> 
> <img alt="Screenshot 2023-09-11 at 12 33 00" width="709" src="https://user-images.githubusercontent.com/13929023/266908286-8f131eeb-d9bf-4912-8e94-6911fa514229.png">

**Comment by rossbulat** [comment]
Completed in https://github.com/paritytech/polkadot-staking-dashboard/pull/1417.
