### ISSUE TITLE
Add status icons in account selection list

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#148]
We'd like to give more context of the accounts at account selection. It would be nice to have icons to reflect important state that a user would be interested to monitor.

If the account is actively staking:

- whether the account has unlock chunks
- whether unlock chunks are available to withdraw
-  if an account has bonded funds but not nominating, mark that staking is inactive, even though it shouldn't be

If the account is in a pool:

- whether the user is the owner of the pool
- whether there are funds to claim

**Comment by TingALin** [comment]
PR 1:
* close button for modal
* remove click outside to close modal
PR 2:
* expand ConnectAccounts modal width
* unify extensions list (left side of modal)
PR3:
* redesign accounts selection items with additional balance / stats
