### ISSUE TITLE
Migrate from Polkadot JS API to Chain API

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#150]
We plan to migrate to CAPI by the initial release. This issue will be split into other sub-issues as and when CAPI is integrated.

**Comment by muddlebee** [comment]
hey @rossbulat 
I am curious what CAPI is? is there any github repo?

**Comment by rossbulat** [comment]
Hi @muddlebee, CAPI (Chain API), is an API to interact with Substrate chains. It is still WIP, but it will likely superseed Polkadot JS API as the go-to API, since it is being build from the ground up with multi-chain support in mind. The link to the repo is here: https://github.com/paritytech/capi
