### ISSUE TITLE
Kusama filter highly - color issue in Dark mode

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-staking-dashboard#172]
On Polkadot the filters are clearly visible
<img width="386" alt="image" src="https://user-images.githubusercontent.com/738724/178942129-901e8799-5050-409b-94f7-7efafbfdaff3.png">

On Westend the filters are clearly visible
<img width="389" alt="image" src="https://user-images.githubusercontent.com/738724/178942183-86b1ad8c-661c-49b8-99f4-d633e24f278d.png">

On Kusama the filters are **BARELY** visible
<img width="393" alt="image" src="https://user-images.githubusercontent.com/738724/178942237-a6e95184-53c2-4dad-ae7d-90e961655e16.png">

**Comment by chevdor** [comment]
@rossbulat so you have a fix that will be deployed later ? I still see the issue.

**Comment by rossbulat** [comment]
The issue is that we cannot deviate too much from the Kusama brand, which is greyscale - there's little to work with 😅

**Comment by chevdor** [comment]
Would that be an option ?

<img width="424" alt="image" src="https://user-images.githubusercontent.com/738724/179055722-b1f9138f-507b-4b88-974e-c366bc85c155.png">
