### ISSUE TITLE
can't submit the nominator pool's commission rate

### ISSUE THREAD

**Issue by eric821031** [paritytech/polkadot-staking-dashboard#1733]
When I try to change my nomonator pool's commission rate, the "submit" button is grayed out.

**Comment by rossbulat** [comment]
Thanks for reporting, I will investigate.

**Comment by rossbulat** [comment]
Hi @eric821031, I have deployed an update to the Github deployment, would you be able to confirm the form is working now? The github deployment is at https://paritytech.github.io/polkadot-staking-dashboard.
Thanks again for reporting!

**Comment by eric821031** [comment]
Yes! It's working now!

**Comment by rossbulat** [comment]
Great! I'll go ahead and close this issue.
