### ISSUE TITLE
`Leave Pool` does not work

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/polkadot-staking-dashboard#1747]
`Leave Pool` only does `unbond`. Is this expected behavior?
I expect that it also should `withdrawUnbonded`.

`src/modals/ManagePool/Forms/LeavePool.tsx` Line 94

```
const getTx = () => {
    let tx = null;
    if (!api || !activeAccount) {
      return tx;
    }

    const bondToSubmit = unitToPlanck(!bondValid ? '0' : bond.bond, units);
    const bondAsString = bondToSubmit.isNaN() ? '0' : bondToSubmit.toString();
    tx = api.tx.nominationPools.unbond(activeAccount, bondAsString);
    return tx;
  };
```

**Comment by rossbulat** [comment]
Withdraw unbonded can only happen after waiting for the unbonding era duration, so 28 eras on Polkadot.

**Comment by frankli-dev** [comment]
Yes, that is for sure.

My concern is for label `Leave Pool`. Because as a user, I think that clicking `Leave pool` will make me leave from a pool so that I can join to another.

But even I click `Leave Pool`, I should also `withdrawUnbonded` to join another pool.

That looks weird. What do you think?

**Comment by rossbulat** [comment]
I agree there should be more context in the leave pool section explaining the actual process. It can be confusing for users to click "Leave Pool" and then be presented with the unbond jargon.

**Comment by frankli-dev** [comment]
Thanks @rossbulat 
I'm closing this now.
