### ISSUE TITLE
Make token amount textfields copy-paste friendly

### ISSUE THREAD

**Issue by ntn-x2** [paritytech/polkadot-staking-dashboard#1754]
<img width="1670" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/6704504/99923a65-048d-43cc-ba62-ca28441e6875">

If someone tries to copy the amounts for bonded funds or unclaimed rewards, the result after pasting it into a different textbox is not what someone would expect. It's a combination of newlines, whitespaces, and weird punctuation symbols. For example, the amount **1,844.336**, when pasted into a simple Mac note, becomes:

```
1
.,
012345678
01234
,.01234
,.
,.0123
,.0123
,.0123456
,.01234
,.0
,.01234
,.012345678
,.0123456789
,.0
,.012
```

This is obviously not very usable, and the only way around it I found is to manually type in those amounts where needed.

**Comment by rossbulat** [comment]
Thank you for posting, I have referenced this in a [Polkadot Cloud issue](https://github.com/polkadot-cloud/library/issues/137), which is where the component source code lives.

I don't believe this has always been the behaviour, but nonetheless we should definitely fix this if we expect other DApps to use the component.

**Comment by ntn-x2** [comment]
Hi. The staking UI still has (it seems) the old UI elements, as the text is still not copy-pastable. I guess the fix has been released with the underlying library, but what about the website? Problem is exactly the same as the one that prompted me to open this issue.
