### ISSUE TITLE
Error when trying to rebond funds being unlocked from bonding

### ISSUE THREAD

**Issue by l0r1s** [paritytech/polkadot-staking-dashboard#1938]
Hi @rossbulat 

I have staked some funds which are vested by bonding them to a group of validator I selected from the Stake > Nominate menu (couldn't but them in a pool). 
For some reason, I tried to unlock the nominated funds so they are in "Unlocking" status with 21 days left to unlock (Era 1369). And then I changed my idea and wanted to rebond them, but when I try to press the "rebond button", it shows a "Oops, Something Went Wrong" and reload following this, it stills doesn't works.
I have an error present in the console. I join some screenshots, feel free to ask me if you need more info.

<img width="602" alt="Screenshot 2024-02-08 at 20 13 25" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/45130584/af965614-4e59-43ea-be49-11cb038ebb3c">
<img width="602" alt="Screenshot 2024-02-08 at 20 13 34" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/45130584/57168982-3433-4970-bb7a-0d2cb5360916">
<img width="565" alt="Screenshot 2024-02-08 at 20 14 07" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/45130584/e6383618-4502-4762-b384-1df612580c77">

**Comment by rossbulat** [comment]
Fixed in https://github.com/paritytech/polkadot-staking-dashboard/commit/607ec6dee7cef57e223ddaa99ee6f8b4a8d9f5fa
