### ISSUE TITLE
Validators doesn't stay favorited

### ISSUE THREAD

**Issue by Lillopi** [paritytech/polkadot-staking-dashboard#2015]
When I mark different Validators as my favorites, they only stay marked as long as I'm not restarting my computer.
After restart there are no more favorites and I have to mark them all over again.
Even when I'm connected with my .Js Wallet, they still not staying marked as favorites.
After asking in Discord, at least one other person has this issue.

**Comment by rossbulat** [comment]
Do you have private browsing or clearing of website data on every session enabled? Favorites are only stored in localStorage - they are not persisted on a backend and only live in your browser. If website data is cleared then favorites will be lost.

**Comment by Lillopi** [comment]
Yes, I use clearing of website data. So that's the answer.
Sad they can't linked somehow to the address your connected with. Maybe it's technically not possible.
Thanks for your response.
