### ISSUE TITLE
Join a pool opens `Members list`

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/polkadot-staking-dashboard#2029]
https://github.com/paritytech/polkadot-staking-dashboard/blob/76f964bdfbab2791a02ce420cb1a3f52b1f6d1d2/src/pages/Pools/Home/Status/useStatusButtons.tsx#L71

<img width="758" alt="Cursor_and_polkadot-staking-dashboard_src_pages_Pools_Home_Status_useStatusButtons_tsx_at_main_·_paritytech_polkadot-staking-dashboard" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/51565705/fe41b878-f002-46ed-bf51-7d4996ffb575">

I'm not sure why this line has been changed in this PR
https://github.com/paritytech/polkadot-staking-dashboard/pull/1816/files#diff-8c7c31c1d2af565d5a3c1fdcb4843343fb5302122c82b0281ed3573fa5352abdR70

It changes the activeTab to `1` (members list).
So when you click `Join Pool` button it goes to `Members list` instead of `All Pools`

**Comment by rossbulat** [comment]
The member list tab was removed and moved to pool stats. Tab 1 is now All Pools.
