### ISSUE TITLE
Active Pools showing All pools

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/polkadot-staking-dashboard#2030]
<img width="567" alt="Pools___Polkadot_Staking_Dashboard" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/51565705/e9401012-a370-4849-9371-347dc6539baa">

On Pools page, `Active Pools` label shows number of all pools.

Is this expected?

**Comment by rossbulat** [comment]
The badge represents the total pool count, irrespective to the list items being shown. 

This is actually not too necessary as the total pool stat is being shown on Overview. Perhaps it is just worth removing that tab to prevent confusion.

**Comment by rossbulat** [comment]
Bade will be removed in an upcoming PR 👍

**Comment by rossbulat** [comment]
@frankli-dev are you on Element or Telegram?

**Comment by frankli-dev** [comment]
> @frankli-dev are you on Element or Telegram?

yes. Telegram. @franklidev

**Comment by frankli-dev** [comment]
> @frankli-dev are you on Element or Telegram?

@rossbulat Are you available on Telegram? Or can you give me your email address? What is the best way to reach out to you?
