### ISSUE TITLE
(Active Era vs Current Era) to fetch eraStakers

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/polkadot-staking-dashboard#2033]
I think
```
ActiveEra is the era that we are on.
CurrentEra is the era that staking is on.
```

So activeEra is when staking is considered which is usually 1 session into era.

Currently the polkadot staking dashboard uses activeEra to fetch the number of active validators, list of validators/nominators, etc.
So at every first session in each era shows the wrong number of active validators. (I mean, different than the polkadotjs app)

Please explain here why polkadot staking dashboard uses activeEra instead of currentEra.
Best regards,

**Comment by rossbulat** [comment]
Referring to the pallet docs, the `CurrentEra` is: "the latest planned era, depending on how the Session pallet queues the validator set, it might be active or not". Whereas the active era is the era "being currently rewarded" - that I interpret as being the active era at which validators are currently receiving era points.

So I think the current setup is correct - the dashboard only shows validators for the active era. I believe the `CurrentEra` prepares validator set before the era actually starts. I may be wrong but discrepencies have not been raised in the past.
