### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by michalisFr** [paritytech/polkadot-staking-dashboard#2034]
@rossbulat I'm sharing the information provided by a user who has trouble connecting Enkrypt to the dashboard.

Browser: Google Chrome 123.0.6312.86
Other extensions: Metamask, Polkadot-JS extension, and others like Kapersky

1. As of 21:30 Japan time today, when they go to dashboard no extension is connected
![4s-Sc0UoeeJtjFUKmcqL9Yd8dY75F9dYNg](https://github.com/paritytech/polkadot-staking-dashboard/assets/45905709/cfa6f23e-5b18-4ba9-9870-e27cfc01fed9)
![SVlT7GYmDQtIBGt7EO0QUOBTcltanb_OHw](https://github.com/paritytech/polkadot-staking-dashboard/assets/45905709/c84ffef0-58d9-4b6b-a907-4ed69af2ef41)

2. When they click "Connect" the connect modal opens up that shows both Metamask and Enkrypt as not installed (no information provided for Polkadot-JS)
![5tOZ24JlhIW0rb2dPcrwJ9OX38Zu9OCHxg](https://github.com/paritytech/polkadot-staking-dashboard/assets/45905709/8ec095f7-101f-440a-8f47-8496c6b17e18)

3. The user then reports: "I pressed the install button several times, but when I opened the dashboard in the end, nothing changed. The connection remains disconnected"

**Comment by rossbulat** [comment]
Could the user try the following:

- Disable all other extensions apart from the one they wish to connect to. Including non-Polkadot extensions as they also interfere with the DOM.

- Clear all website data for staking dashboard so local storage is reset. 

After this, refresh the app and attempt to connect the single web extension of interest. 

If this is successful, turn on the other extensions one by one until the breakage occurs. This will determine what extension is causing the break.

**Comment by rossbulat** [comment]
> I pressed the install button several times

We do not have install buttons on the dashboard - just the "not installed" text and a link to the extension website. The install button would be on the Chrome Store.

**Comment by michalisFr** [comment]
@rossbulat Another user who has Enkrypt and Subwallet installed (and no other extensions) described the following situation:

1. They had this issue (where the extensions showed as not installed) on Brave and Chrome. Then Chrome worked on its own and then it broke again.
2. They followed your recommendations to clear the site's data (and even did a system restart) but with both extensions enabled the problem persisted on both browsers.
3. Then they disabled Subwallet on Brave and the problem persisted.
4. Once they disabled Enkrypt though on Brave and enabled Subwallet, they were able to connect to their Subwallet account.

So, it would seem Enkrypt is culprit? I haven't confirmed whether any of the Ledger users have Enkrypt installed.

**Comment by Ddincer85** [comment]
Same problem here

**Comment by michalisFr** [comment]
@rossbulat Another user that was trying to connect directly with Ledger reported the following steps:

1. Trying to Connect with my wallet:
<img width="1430" alt="zpW24SpV8XvPLgbJibATt8172Ar0Ejcpzg" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/45905709/6a3c7a18-d094-417e-8579-a823b387e46d">


2. Selecting Ledger > USB (as usual but now it is not connecting)
<img width="872" alt="QyT_0zW-E-1qqm9RLx9q0O6ZcNdYC_Xyhw" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/45905709/65379129-cb46-45f6-b8c5-5a9a90fed59a">


3. Clicking DONE in order to connect with my Polkadot Account to access my Staking funds. Unfortunately it does not Connect and I go back to the Page of the Step #1
<img width="857" alt="Zi1IqQitQ2y09oluLhcnBx2sEgwYa-DhbQ" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/45905709/7ebe61b2-ea71-46d0-b05b-e94e048b0ea5">


They didn't report browser version or any extensions installed, but after a recommendation from Ledger to clear the cache the problem was resolved.

**Comment by Juanma0x** [comment]
About connecting Enkrypt to the wallet. It can be done by turning off Ethereum dApps interactions. Steps to reproduce:

1. Open Enkrypt.
2. Go to "Settings" > "General" > Activate "Turn off Ethereum for 1 hour"
3. Open or refresh the Staking Dashboard.
4. Connect to Enkrypt (it should appear as installed)

![image](https://github.com/paritytech/polkadot-staking-dashboard/assets/120041850/c6dc083a-17f2-4223-add6-184a4a28f64c)
