### ISSUE TITLE
The logic to calculate `fundsFree`

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/polkadot-staking-dashboard#2072]
https://github.com/paritytech/polkadot-staking-dashboard/blob/14188991f201ffd78cb704eae68c6e5a29e7c960/src/pages/Overview/BalanceChart.tsx#L111-L121

Here `fundsReserved` is already plankToUnit. 

But `allTransferOptions.freeBalance` is not.
How can we do math between plankToUnit and plank?

https://github.com/paritytech/polkadot-staking-dashboard/blob/14188991f201ffd78cb704eae68c6e5a29e7c960/src/pages/Overview/BalanceChart.tsx#L115-L116

This does not make sense.

**Comment by frankli-dev** [comment]
https://github.com/paritytech/polkadot-staking-dashboard/blob/14188991f201ffd78cb704eae68c6e5a29e7c960/src/contexts/TransferOptions/index.tsx#L56-L76

I noticed that `allTransferOptions.freeBalance` is already deducted by `feeReserve` & `edReserve`

**Comment by frankli-dev** [comment]
@rossbulat Please review this.
This is from my understanding. I want to know if I'm on the correct way
https://github.com/paritytech/polkadot-staking-dashboard/pull/2075

**Comment by rossbulat** [comment]
Thanks @frankli-dev, there was an issue I identified regarding the reserved value thanks to your investigation. 

The `fundsFree` being displayed is different from `freeBalance` in transfer options, as the `fundsFree` also has the reserved balance deducted from it, that consists of the existential deposit and the reserve amount configured on the Overview page.

It is evident that the variable names here should be improved to make it obvious whether they are in plank or unit format. Perhaps this can be tackled in a future PR.

**Comment by rossbulat** [comment]
`fundsFree` and `freeBalance` are 2 different values. `fundsFree` does not take into consideration other locks on the account E.g. OpenGov locks, whereas `freeBalance` only takes into consideration the `staking` lock. This is indeed confusing and could well be improved.

**Comment by rossbulat** [comment]
Fixed in #2075

**Comment by frankli-dev** [comment]
> Fixed in #2075

@rossbulat Are you available on telegram?
