### ISSUE TITLE
Pending payouts doesn't exist

### ISSUE THREAD

**Issue by chuacw** [paritytech/polkadot-staking-dashboard#2100]
Pending payouts doesn't exist, but the UI is showing there's pending payouts and the claim button is enabled.

**Comment by rossbulat** [comment]
Hi @chuacw, thanks for posting the issue. 

Would you be able to try to clear local storage completely? I believe stale local storage data may be the cause of this issue. If it still persists then I will look into what is happening.

**Comment by chuacw** [comment]
Cleared local storage, but it's still happening.
I wonder if the code checks that the payout has already been claimed successfully?

**Comment by chuacw** [comment]
https://github.com/paritytech/polkadot-staking-dashboard/blob/9a4d4af2804712cebb913a83836a33b2f627e269/src/contexts/Payouts/index.tsx#L198-L206

Not sure if I'm reading these lines correctly, L202-L206 doesn't seem to be removing claimed entries from unclaimedRewardsEntries.

**Comment by chuacw** [comment]
This has been resolved.
