### ISSUE TITLE
Error when trying to chill nominations

### ISSUE THREAD

**Issue by keeganquigley** [paritytech/polkadot-staking-dashboard#214]
There seems to be an issue when trying to chill via the dashboard. I believe it to be a UI issue as I tested it on multiple networks and both Chrome/Brave browsers, but the problem remains. Chilling on Polkadot-JS works fine.

When selecting the **Stop** button, it doesn't display an estimated tx fee, and upon submitting it displays this error:

<img width="1434" alt="bug" src="https://user-images.githubusercontent.com/35080151/184932927-66da4837-005e-4628-a2f3-bc1162571a39.png">

The same thing happens when trying to manually select any amount of nominators followed by the **Stop Nominating Selected** button. I'm connecting with Polkadot-JS browser extension.

Thanks!

**Comment by rossbulat** [comment]
HI @keeganquigley , can you check if this is happening on the github deployment? There have been some updates.
The link is https://paritytech.github.io/polkadot-staking-dashboard/#/overview

**Comment by keeganquigley** [comment]
Thanks @rossbulat it does work properly on this deployment, for both networks! Thanks.

**Comment by rossbulat** [comment]
Thanks for confirming :)
