### ISSUE TITLE
Remaining Nomination Pool Features

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#222]
This is an issue to communicate the outstanding features needed for a fully-featured nomination pool dashboard.

#### Misc / time permitting:
- Bulk permissionless unbond / withdraw. (batch limit is 10922 calls)
- UX to show funds are ready to be withdrawn from member and a circular timer (chart.js is too heavy for this) to show progress to unlock era).

Builds upon what was introduced in #212, #224, #230, #234 and #237.

**Comment by dvdplm** [comment]
Are there any outstanding tasks left on this ticket? At a quick glance it seems like no?

**Comment by rossbulat** [comment]
> Are there any outstanding tasks left on this ticket? At a quick glance it seems like no?

The functionality is there, I am just keeping this issue open as a reminder to polish some things around the remaining tasks. They are not mission critical, just nice to haves! I'll update the description to reflect the current intentions.
