### ISSUE TITLE
UX Feedback

### ISSUE THREAD

**Issue by TThanachaipornsakun** [paritytech/polkadot-staking-dashboard#233]
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/101091988/188575971-11b4e811-faac-44b7-b4c5-a0fc4058b4be.png">

**User-Facing Problem:**
"Not connected" doesn't make sense if the wallet isn't installed on the users chrome profile.   

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/101091988/188576844-282cbf66-4f54-4196-8631-f0975df152d1.png">

Solution: Change the text from “Not Connected” to “Not Installed” for the wallet that isn’t in the user’s browser. 

Leave “Not Connected” to the wallet that is installed on the user’s browser

**Comment by TThanachaipornsakun** [comment]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/101091988/188577979-447f7c01-f9cd-4f19-8ac7-207bd7863420.png">

I think instead of having the user click on the wallet can slide into another screen to show account details, it would be great to have the following content as an accordion. Connecting the wallet and disconnecting should be in the same screen or flow. 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/101091988/188578421-910f9b62-45bc-40a2-9c41-d7d7de5ffbc3.png">

The modal can be positioned top center, instead of center to cater to the expanding nature of the modal (if we implement the accordion for wallets

**Comment by TThanachaipornsakun** [comment]
![UX Bug](https://user-images.githubusercontent.com/101091988/188580650-dbdf9891-2e21-4810-8254-535a5f3ce033.png)

The user disconnected their wallet from their account. Goes back to the wallet selection page and still has the wallet connected. I think instead of using the word "disconnect", use the term "Unlink Account from Dashboard" would be more understanding. 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/101091988/188582252-c89f428e-b2e6-4e37-8309-a4d46040c76a.png">


"Connected wallet: and "Disconnect" seems somewhat related because of the language. Having two concept connect & link, instead of just "connect", would help the user understand why their wallet is still connected and their account disconnected from the dashboard.

**Comment by TThanachaipornsakun** [comment]
Please apply gestalt’s principle of proximity (https://lawsofux.com/en/law-of-proximity/) to separate “Order” and “Exclude”. It felt like the tag "lowest commission" is along with "inactive validator", "oversubscribed" etc... tags. This will confuse new users when they are interacting with filtering.

From This: 
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/101091988/188585387-aed02958-cb49-47ba-9d80-886629df5919.png">

To This:
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/101091988/188585524-6aee5839-2e38-46a0-8533-815697742d1c.png">

**Comment by rossbulat** [comment]
Stale / being addressed now.
