### ISSUE TITLE
show all validators and send staking transcation ?

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/polkadot-staking-dashboard#250]
1.  i want to see all validators
2. i can choose many validators and send staking transcation

**Comment by rossbulat** [comment]
Hi @LXHLeaner, 
1. Go to the Validators tab to view and search for validators.
2. You can do this in a number of ways. You can accumulate favourite validators and add them when setting up your nominations. Or you can automatically generate a list of nominations in various ways, and then tweak the list (add or remove other validators) as you please.

Is there something we are missing from your expectations?

**Comment by LXHLeaner** [comment]
as a exchange，i want to build transaction about staking ,whether or not you can provide api?

**Comment by rossbulat** [comment]
I recommend the Polkadot JS API to do this.
