### ISSUE TITLE
Make Substrate Connect Default Connect Option

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#257]
We want light client connectively to become the default way to interact with Substrate chains.

On top of this, personally speaking Substrate Connect actually connects to networks in a more stable manner than RPC does in various settings I've subjected the staking dashboard to, including hotel wifi and hotspots in various geographies.

We still have the "Brave browser WebSocket issue" to resolve, but it would be great to then do some final testing and determine a good time to make it default.

At this time I would also like to experiment with some help content in-app to explain what Substrate Connect is and how to install / use it, & its benefits.

@wirednkod, I'm sure you're much more familiar with the Brave / other issues and can make a good call when the right time to do this will be.

**Comment by wirednkod** [comment]
Thank you @rossbulat . Can you please elaborate on what you mean, when you mention "Brave issue"?

**Comment by rossbulat** [comment]
Yes, this documented Brave browser WebSocket limit issue:

<img width="735" alt="Screenshot 2022-10-03 at 14 16 56" src="https://user-images.githubusercontent.com/13929023/193586636-0916f5f8-28e7-4dda-988f-c6f4306a86ef.png">

**Comment by wirednkod** [comment]
To be fair and to clarify this is not an issue. Brave decided to go that path and keep the active socket amount to 10. Im not expecting any change on that. We can always default light clients and keep the notice for brave browsers

**Comment by wirednkod** [comment]
> @wirednkod, I'm sure you're much more familiar with the Brave / other issues and can make a good call when the right time to do this will be.

Light client is experimental at the moment, but I can say that we CAN add it as default with the following extra dev tasks:
- In case Smoldot light client panics, to switch to the rpc-client
- In case connection takes too long (peers = 0) then give an option to user to switch to RPC
- Show in a visible place at the UI that light client is used (at the moment its visible only when pop up appears)

What do you think @rossbulat ?

**Comment by wirednkod** [comment]
> > To be fair and to clarify this is not an issue. Brave decided to go that path and keep the active socket amount to 10. Im not expecting any change on that. We can always default light clients and keep the notice for brave browsers
> 
> From what I recall there is a work-around coming for this problem in the near future? I'm envisaging a time after that to move forward with this.  

Yes. You are referring to the WebRTC integration into Smoldot. This will take some time still, though, i will keep you informed. In the meantime if you feel positive enough, we can proceed with the above solution for now
