### ISSUE TITLE
Kusama Staking Dash allows stake amount of 0

### ISSUE THREAD

**Issue by RadMenace** [paritytech/polkadot-staking-dashboard#259]
Kusama staking dashboard allows staking amount of 0 and seems to default to it. Attempted to stake using the Kusama staking dashboard several times and successfully staking 0 every time, getting charged a transaction fee. 

 calls
[
  {
    "callIndex": "0x0600",
    "args": {
      "controller": {
        "id": "//taken out for privacy purposes//"
      },
      **"value": 0,**   <<< VALUE DEFAULTED TO 0 EVERY TIME
      "payee": {
        "stash": null
      }
    }
  },
  {
    "callIndex": "0x0605",
    "args": {
      "targets": [
        {
          "id": "DDhVgn62SE2riWjS6U4AaYtfLNKuFxqTU32EnqAtAuxqM58"
        },
        {
          "id": "CzBdHbDPDwREbHEC8czQ7HvpqAKofN3bu6vPaa5BxoBE8vq"
        },
        {
          "id": "Cs1jHXYHxZyWKsGPvYY1BknhLdpNa1iXGja4Kn8hQZs7BsH"
        },
        {
          "id": "CzugcaXQoyXDnWWYUXQ1Yain1GZNCLQ76xGy3rny2h6dokB"
        },
        {
          "id": "GHXKyWqC2Jm69XmVGjbQWBC7XVtbwRHszYKAVa5LFxFSEmG"
        },
        {
          "id": "CwTzXx7Ga3CuFzJSbc4xHphY3dryFxAHwno1DR7o2tPKpAg"
        },
        {
          "id": "F358tdKgqzU2YivnRVVZT7QgyScfPWR66c55YvLq4zeQvih"
        },
        {
          "id": "DahPwrmRmSEjNCqEehzuGddTmvFnk9q7g6wo4saRqBQ18RK"
        },
        {
          "id": "HTyzs9XAxUpHpNe7Kwhp3M5kCJuxFm4AYRCpYjcHdhiVDFE"
        },
        {
          "id": "DJQLfZxrnhnssEPFxEpYbowDdNsU3N4gMXStw84eko1VaCw"
        },
        {
          "id": "Czugca2tdce8UvUpquc8j3GNgbN4tgFb1uAgZewLDRat8WF"
        },
        {
          "id": "DdHopCbdSzdf8d1eqdwVGs6uDAyYTdSpytv2Juc3vuRxGNa"
        },
        {
          "id": "J6RxM7PgTM5c3tA9JCQdvoyHhkgWrNab2B4n5iDSprMTdSm"
        },
        {
          "id": "E2pSzVjX9RktXQRcR2DpMGQMf6bFCMhUnY3zRiR18RmdD8N"
        },
        {
          "id": "Fktq9ciMBhSnx4MJbaQqgy651HXpdJLLKDJH4Ahy2yEbrv2"
        },
        {
          "id": "EygmNkGy9vnTsM3wkHLYBt212TJPLDDptVQxuhfihggdkTY"
        }
      ]
    }
  },
  {
    "callIndex": "0x0608",
    "args": {
      "controller": {
        "id": "//taken out for privacy purposes//"
      }
    }
  }
]

**Comment by rossbulat** [comment]
Was this tested on the GitHub deployment or on staking.polkadot.network?

I have rolled out a fix with a pending PR to production. Please confirm that it is working on GitHub deployment

**Comment by RadMenace** [comment]
The issue was on the staking.polkadot.network - looks like the GitHub deployment fixed this.
