### ISSUE TITLE
First build, error linked to source maps of @substrate/connect not present

### ISSUE THREAD

**Issue by l0r1s** [paritytech/polkadot-staking-dashboard#260]
Hi @rossbulat ,

I was trying to launch the project locally for the first time and I was welcomed with many webpack errors about not being able to find the source maps for @substract/connect, is it something normal ? Do you ignore them ?

Environment: Node 16.17.1 / yarn 1.22.19

![Screenshot from 2022-10-07 09-47-13](https://user-images.githubusercontent.com/45130584/194488442-98fac76a-efc4-4c32-969e-34037ff35c50.png)

**Comment by rossbulat** [comment]
@wirednkod Can we prevent these warnings?

**Comment by wirednkod** [comment]
@rossbulat We will in the next version - there is a [PR](https://github.com/paritytech/substrate-connect/pull/1285) for that. It troubles me though - as I thought it was resolved [here](https://github.com/paritytech/substrate-connect/issues/1196)
