### ISSUE TITLE
Testing organization

### ISSUE THREAD

**Issue by l0r1s** [paritytech/polkadot-staking-dashboard#263]
Hi @rossbulat,

I'm starting to investigate setting up testing for the repository, I read your paragraph in the README about it, and I want to challenge you with some solutions I've come around to:

- Unit testing of contexts in almost isolation is the most crucial part in my eyes because it reflects pure logic; given some contexts depend on others, we don't want actual HTTP/RPC/WS connections; the project will significantly evolve shortly, we should make the minimum usage of mocks of the implementation code else the tests are going to be flaky if we change any implementation detail. For this, I suggest testing only the returned methods from the context providers.

- Integration testing of contexts with real HTTP/RPC/WS connections 

- Unit testing of components in isolation with Storybook (as you suggested); this will enable us to have a quick view of the available components and document their usage simultaneously.

- E2E of predefined workflows as you started to define in the README using Cypress ?

Keep in mind that I've only started diving into the code and need to accustom myself to the logic / SDK you are using, but when some tests are ready, I could help you set up the Gitlab pipeline.

**Comment by rossbulat** [comment]
Hi @l0r1s , thank you for posting! Is there a channel we can connect on to discuss this further?

**Comment by l0r1s** [comment]
@rossbulat as you prefer, Matrix seems to be used on your side ?
