### ISSUE TITLE
Active validators are mixed up

### ISSUE THREAD

**Issue by stakeworld** [paritytech/polkadot-staking-dashboard#286]
Hi,

The active and inactive validators display seems to be unstable in the community tab; I have 4 validators active there, in https://staking.polkadot.network/#/community it changes on resync (while the situation is unchanged)
<img width="1194" alt="Schermafbeelding 2022-10-23 om 13 47 21" src="https://user-images.githubusercontent.com/106294967/197390340-503b40cc-0c3a-48b3-87d5-d4496f6428f5.png">
but in reality the active validators are different:
<img width="400" alt="Schermafbeelding 2022-10-23 om 13 47 34" src="https://user-images.githubusercontent.com/106294967/197390360-c64b230c-a558-4098-a494-430cbd385537.png">

When I refreshed a few seconds later I get
<img width="1189" alt="Schermafbeelding 2022-10-23 om 13 50 47" src="https://user-images.githubusercontent.com/106294967/197390605-362e7ea4-7e34-4dcf-a740-c0c7b480881b.png">

On a new refresh it changes again. In the validator tab everything is stable and correct. Using with chrome polkadot polkadot.js extension

**Comment by rossbulat** [comment]
Thank you for reporting. This may be a result of a `shuffle` function we have in there. I will investigate further.

**Comment by rossbulat** [comment]
@stakeworld , can you confirm whether the issue resolved on the github deployment please?: https://paritytech.github.io/polkadot-staking-dashboard/#/community

**Comment by stakeworld** [comment]
> @stakeworld , can you confirm whether the issue resolved on the github deployment please?: https://paritytech.github.io/polkadot-staking-dashboard/#/community

@rossbulat Indeed, working as expected now
