### ISSUE TITLE
entries() api requests are incorrectly calculated with light client

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#300]
API `entries()` requests are returning the incorrect data when connected to Light Client. This impacts eraStakers, validators, bondedPools and poolMembers `entries` requests.

cc @wirednkod

### TODO

- [x] needs testing / identify any further bugs.

**Comment by wirednkod** [comment]
[This PR](https://github.com/paritytech/smoldot/pull/2947/files) should solve the issue
