### ISSUE TITLE
Slashes show up as positive payout

### ISSUE THREAD

**Issue by coderobe** [paritytech/polkadot-staking-dashboard#303]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/8442384/198995326-8812d8c0-7309-46bf-a5f6-59007c2225b2.png">

**Comment by rossbulat** [comment]
Thanks for reporting, I will investigate.

**Comment by rossbulat** [comment]
I have removed slashes from the payout graphs - they will still be displayed in the list below them though. I will look into how to further display slashes in the future.
Thanks for reporting!
