### ISSUE TITLE
Replace `moment` with native `Date`

### ISSUE THREAD

**Issue by wirednkod** [paritytech/polkadot-staking-dashboard#313]
`momentjs` has [stopped developing](https://momentjs.com/docs/#/-project-status/) for some time now and [recommends alternatives](https://momentjs.com/docs/#/-project-status/recommendations/).

Since it is not heavily used in Polkadot Staking Dashboard maybe its a good idea to consider replacing it.

**Comment by rossbulat** [comment]
Fixed in #389
