### ISSUE TITLE
New ledger accounts showing as read only

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-staking-dashboard#335]
There seem to be a bug when adding new accounts from a Ledger to the PolkadotJS extension.
In the dashboard those show up as ReadOnly despite being available in the extension.

I think this happens only if you:
- say you have 2 ledger accounts A and B. Testing is easier if B is controller for A
- ensure that A is in the polkadot js extension
- ensure that B is NOT in there
- open the dashboard
- switch to the right network
- observe that A is visible and not readonly but B appears readonly
- add B to the polkadot js extension, observe that it did not fix the issue
- now switch network and come back
- both A and B are now visbile and not read only

I figured out that switching network back and forth (say going to Kusama and coming back on Polkadot) solves the issue.
I suspect there is some caching that is refreshed only when the network is changed. It could be useful to avoid that to have a function to reload accounts, and that could be suggested whenever so apparently read only accounts are detected.

**Comment by rossbulat** [comment]
Thank you for reporting, I will look into it.

**Comment by rossbulat** [comment]
HI @chevdor, can I ask if this is still happening on https://paritytech.github.io/polkadot-staking-dashboard/#/overview?
