### ISSUE TITLE
Amend misleading locked balances graph

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#35]
The Overview balance graph needs to be amended to take into consideration locked / vested funds that can be staked. 

<img width="521" alt="Screenshot 2022-05-10 at 11 47 21" src="https://user-images.githubusercontent.com/13929023/167611818-5f06d11b-1d8e-44a6-b2f8-7e01cd2c3fa7.png">

Right now we have 2 issues:
- it looks like the greyed-out locked funds are inactive.
- The locked funds take into consideration staked funds *and* other vested funds that are locked (non-transferrable). These non-staked locked funds could be staked, and need to be communicated in the graph as a separate label to the locked staked funds.

This will be useful for the user to know - if their funds are locked for whatever reason, they might as well utilise them and stake them.

Additional API calls need to be made to determine these numbers, and need to be plugged into the donut chart with additional labels.

API calls of interest:

- `vesting.locks` to get amount locked and block duration
- `balances.locks` to get locked array, id and reasoning

**Comment by hamidra** [comment]
I'm wondering do we need to indicate the transferrable balance here at all, since the app won't let the users send or transfer the funds. 
 If I'm not missing anything, one way to simplify this view might be to just show them 'staked' and  'free to stake' balances.
That way for example if they have locked funds for governance we can still show it here as sakable. In this view, user probably won't care how much they have locked for governance or other misc cases and only want to see how much of their balance they can use to stake.

**Comment by rossbulat** [comment]
> I'm wondering do we need to indicate the transferrable balance here at all, since the app won't let the users send or transfer the funds.
Yes indeed. I think the main challenge is to deduct the staked balance from the remaining "free to stake" balance. As some of that "free to stake" balance will be locked or vested funds.

> 'staked' and 'free to stake'
That would work very well.

> if they have locked funds for governance we can still show it here as stake-able
Exactly. If we can communicate this clearly with the above 2 labels, would work super well.

> user probably won't care how much they have locked
I think the chart itself should group the "available to stake" number, and perhaps we can expand in the future via a hover or additional modal the exact numbers.

**Comment by rossbulat** [comment]
I've added a new function to the Balances context - [`getBondOptions()`](https://github.com/paritytech/polkadot-staking-dashboard/blob/549017641c02bbbf50c73d3a2bfcb04917f8d2b8/src/contexts/Balances/index.tsx#L245). It can be used like so:

```
const { activeAccount } = useConnect();
const { getBondOptions } = useBalances();
const { totalUnlocking } = getBondOptions(activeAccount);
```

The `totalUnlocking` value should help when doing the remaining stake-able locked balance.
