### ISSUE TITLE
UX: Enhanced Validator Metrics Card

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#36]
This issue is intentionally vague as to explore various layouts and designs for an enhanced validator metrics card.

The current card simply displays the validator's era points history. This is mostly a means of bootstrapping the boilerplate for expansion in future iterations:

Here is a Zug Capital node as an example:
<img width="888" alt="Screenshot 2022-05-11 at 10 21 55" src="https://user-images.githubusercontent.com/13929023/167816175-190d7375-e7ef-45aa-a7b8-cdb2f2d12197.png">

We see this modal being expanded with useful stats and metrics. Some of them we've identified are:

- additional graph to show when validator was active or inactive.
- when validator was active, how many era points on average were they making.
- percentage of active eras the validator was receiving points.
- average commission / network average commission.
- the self stake of the validator.
- whether the validator is validating parachains, era points from paras / relay?

UX proposals and concepts are very welcome.

**Comment by dnlklmn** [comment]
**First round of ideas + accompanying questions:**

[Designs in figma](https://www.figma.com/file/5jmUWCe6fpRDIFz2S4MhbV/Staking-Dashboard?node-id=301%3A1510)

[Some ideas on graphs](https://www.figma.com/file/5jmUWCe6fpRDIFz2S4MhbV/Staking-Dashboard?node-id=306%3A3297)

**Questions:**
- is not earn = inactive? as far as i could tell you can not-earn while still being active. do we need to differentiate between these? which one are you more interested in?
- should be able to adjust scale of time, will figure that out next (+label arrangement)

[Structure of card](https://www.figma.com/file/5jmUWCe6fpRDIFz2S4MhbV/Staking-Dashboard?node-id=306%3A3295)
**Suggested overall structure: **
- important checks (oversubscribed, para validator, etc)
- graph + set time frame
- activity/commission/stake/history

**More questions:**
- self stake is called 'own stake' in pd.js should we keep that?
- should we include all indicators that pd.js shows in one line (next session, para validator, etc.)? i now included some
- should we include [other details](https://www.figma.com/file/5jmUWCe6fpRDIFz2S4MhbV/Staking-Dashboard?node-id=306%3A3298) pd.js has, like address, balance details, & identity?

**Comment by rossbulat** [comment]
Great work @dnlklmn, I think this adequately answers the questions around how the card will be formatted. The added shading of the graphs do a better job at showing when the validator was active too.

> self stake is called 'own stake' in pd.js should we keep that?

I'm assuming stick to the official terminology. We can always have an assistant definition in place to expand on the terms.

> should we include all indicators that pd.js shows in one line (next session, para validator, etc.)? 

These are reasonable stats to show as a secondary purpose IMO, such as the way the second and third graphs place these stats at the bottom of the card:

<img width="303" alt="Screenshot 2022-05-19 at 09 22 27" src="https://user-images.githubusercontent.com/13929023/169247757-f807b9ef-3251-4a86-8f41-e5b8e0349e2c.png">

> should we include [other details](https://www.figma.com/file/5jmUWCe6fpRDIFz2S4MhbV/Staking-Dashboard?node-id=306%3A3298) pd.js has, like address, balance details, & identity?

Identity has been an important metric for users choosing validators. We could expand to support some more details that validators provide, such as email address, twitter etc. I think communication between nominators & validators should be promoted to give nominators more tools to gauge which validators they choose, and for validators to better promote their performance on social media etc.
