### ISSUE TITLE
UX feedback

### ISSUE THREAD

**Issue by paulozago07** [paritytech/polkadot-staking-dashboard#371]
Hello, 
members of the community seek to know the possible rewards of the staking pool, it can be very interesting to have this information very visible
![image](https://user-images.githubusercontent.com/94564832/203140833-e6885223-6085-4223-9fb7-09ee0a640cd6.png)

I've read about having information in the pool description, but the panel doesn't favor many characters...
my suggestion is to add comunnity tab to pools helping in communication with pool members
![image](https://user-images.githubusercontent.com/94564832/203139250-4569564e-3ece-4f5a-935a-c82956308069.png)

![image](https://user-images.githubusercontent.com/94564832/203139771-6dfd1285-a965-4149-a80f-e956fde50f5a.png)
Information is currently incomplete.

🤙

**Comment by rossbulat** [comment]
Thanks for your feedback, in general:- 
* regarding adding a 4th statistic to a stat row, this is not viable for smaller screens (without hiding it). But I agree that rewards rate per pool would be a very good thing to have.
* the last screenshot: The text is overflowing its container and long pool names sometimes are elegantly clipped with ellipses. This is unavoidable as users are free to input pool name length they desire. Perhaps a tooltip displaying the full name would be a welcome addition.

**Comment by paulozago07** [comment]
If we reduce the length of the 3 boxes, manage to place this 4 box with the rewards in an elegant way. the 3 boxes have plenty of room
