### ISSUE TITLE
timers missing a 0

### ISSUE THREAD

**Issue by wirednkod** [paritytech/polkadot-staking-dashboard#383]
Countdown timer is missing 0s when numbers have 1 digit.
See screenshot below:

![image](https://user-images.githubusercontent.com/5408605/203848700-70db90c7-8545-43b3-9574-9d47b9b4d669.png)

**Comment by rossbulat** [comment]
This is known and not considered a bug. However it could be a good Polish. This also should wait until moment is deprecated

**Comment by rossbulat** [comment]
Fixed in #389
