### ISSUE TITLE
State doesn't get updated on controller's account import

### ISSUE THREAD

**Issue by jsidorenko** [paritytech/polkadot-staking-dashboard#386]
There is a requirement to have the controller's account connected.
Once I imported that account into my extension, that change wasn't propagated into the UI. Even when you refresh the page, it keeps saying that you need to import your controller's account.
The only thing that helped me, was a manual clearing of the local storage.

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/5252494/204008413-4974142c-2387-42ef-9f86-feb899ada595.png">

**Comment by rossbulat** [comment]
Is this still happening @jsidorenko ?

**Comment by jsidorenko** [comment]
I don't know, I cleared the localstorage and that error disappeared. You can try to remove your controller's account from the extension, then connect with the main acc and check
