### ISSUE TITLE
Click to reload button doesn't work

### ISSUE THREAD

**Issue by jsidorenko** [paritytech/polkadot-staking-dashboard#387]
The "Click to reload modal" button does nothing.
P. S. And doesn't really look like a button or a link.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/5252494/204008606-311ec947-10d8-4ae9-8832-ea79beff4090.png">

**Comment by rossbulat** [comment]
Thanks. This is fixed in the codebase pending PR.

**Comment by Shahab222** [comment]
Hi, this still is not working.
