### ISSUE TITLE
Make StatBoxList to take Items as children instead of props

### ISSUE THREAD

**Issue by hamidra** [paritytech/polkadot-staking-dashboard#39]
Re: #33 
Currently, StatBoxList takes a list of item attributes as a ```items``` prop and renders them inside the component.
This makes it hard to customize the StatBoxes, e.g. for #33 which we want to render a more customized statBox.
We can make the StatBoxList accept the inner Items as children components so they can be customized for different types of stats.

**Comment by rossbulat** [comment]
Great improvement 👍
