### ISSUE TITLE
Sidebar - Group "Help/Resources" and "Feedback" in the same "Support" category

### ISSUE THREAD

**Issue by polkadotcurry** [paritytech/polkadot-staking-dashboard#396]
Source: Natalie T via Staking Release Channel

- Change "Help" to "Resources" (because it's only resources to read)
- Have them both under the heading "Support"
- Rename URL (if possible) from /feature-requests to /feedback (and have 2 boards in there)

![image2](https://user-images.githubusercontent.com/106126551/204340502-8f4e9f31-7192-457f-bd3b-b15f0d7ec599.png)

**Comment by rossbulat** [comment]
Thanks. These changes are now in the codebase.
