### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by Shahab222** [paritytech/polkadot-staking-dashboard#417]
Hi, I’ve got to 97% on staking, then this happened. 
![31C1ECFF-E6E8-4367-A3B2-DA0698AE512B](https://user-images.githubusercontent.com/79801752/205496456-d37254a3-fd40-4557-96bf-5ec21d640b58.jpeg)

reload not working. There is no link on this

**Comment by rossbulat** [comment]
Is this on the Payee modal? If so we are aware of this and awaiting an update to be deployed.

**Comment by Shahab222** [comment]
Ok, thanks look forward to the update
