### ISSUE TITLE
Pool Stats Text Amendments

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#490]
Slight adjustment to make pool stats easier to understand.

- [x] Minimum Join Bond -> Minimum to Join Pool
- [x] Minimum Create Bond -> Minimum to Create Pool
- [x] EN and CN text amendments

<img width="642" alt="Screenshot 2022-12-23 at 09 42 49" src="https://user-images.githubusercontent.com/13929023/209260346-7b7605fe-ffe4-4d41-b4f8-3d74ecfe044d.png">

**Comment by TingALin** [comment]
Minimum To Join Pool
Minimum To Create Pool
