### ISSUE TITLE
Move setup logic from UI to new Setup context

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#498]
The setup logic (setup progress, whether you are on a setup page) is currently in the UI context, and needs its own home in a new Setup context. Change `useUi` to `useSetup` where used.

State items:
```
onNominatorSetup
onPoolSetup
setup / setupRef
```

useEffect items:
```
// move away from setup pages on completion / network change
useEffect(() => {
 ...
```

Functions:
```
setupDefault
getSetupProgress
getStakeSetupProgressPercent
getPoolSetupProgressPercent
setActiveAccountSetup
setActiveAccountSetupSection
```

**Comment by TingALin** [comment]
I think i can move the Syncing items from the useEffect() too?

**Comment by rossbulat** [comment]
Syncing related logic stays in UI. We only want to move the setup logic.
