### ISSUE TITLE
Add pooling functionality

### ISSUE THREAD

**Issue by hamidra** [paritytech/polkadot-staking-dashboard#51]
Add functionality to the Pools page to let the user:
- create a pool
- join a pool
- unbond from pool or destroy its pools

**Comment by rossbulat** [comment]
We can abstract a lot of [`ManageBond`](https://github.com/paritytech/polkadot-staking-dashboard/blob/master/src/pages/Stake/Active/ManageBond.tsx) for managing your pool bonds. This would keep the layout consistent with the Stake page - Pool Roles could go elsewhere.

I could jump onto the abstraction if needed.

**Comment by hamidra** [comment]
Agreed. We should keep the flows consistent as much as possible to make the UX  easier for the end-user. There are some differences in the pooling that need more thought regarding unifying the flows. MangeBond is a good candidate for sharing between the two use-cases. We can discuss more how the new design can look like.

**Comment by hamidra** [comment]
addressed by #95
