### ISSUE TITLE
Add locale key ordering check to locale:validate script

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#513]
The last thing for now on the locale validation side - checking if the keys are alphabetically ordered in the validate CI. There will be instances where we / external devs will forget to run the ordering script for a PR. Let's ensure we are bulletproof here.

- Expand `.scripts/localeValidate` to do multiple jobs: missing keys + alphabetical order check.
- Leverage the code already introduced in `.scripts/localeOrderKeys` to check if `orderKeysAlphabetically(json)` is the same as `json`.

Think about how you will structure the functions without repeating the code. E.g. moving some functions that are used multiple times into a `utils.js` file, or `locale.js` file. I will leave it up to you @TingALin.

Addresses #445

**Comment by TingALin** [comment]
For the order checking, i think i will implement ('a'<''b') method to do it, as its time complexity: O(N), and checking if it's same as json would be O(N*log(N)). Please see the detail at : https://www.geeksforgeeks.org/check-if-the-characters-of-a-given-string-are-in-alphabetical-order/

**Comment by rossbulat** [comment]
Interesting, a lot of this is what `sort` does anyway, only sort will not exit early if we find a switch is needed. It keeps going all the way through & re-orders the entire object. This is okay to use with `json === ordered(json)`, we are not processing millions of translations so CPU time is not a bottleneck. For code simplicity, reusability and modularity, lets keep things simple and use `orderKeys(json) === `json`.
