### ISSUE TITLE
Change unbond duration from eras to time left

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#520]
Replace "X eras" in `modals/UnlockChunks/Overview.tsx` with an estimated time left function.

<img width="640" alt="Screenshot 2023-01-01 at 17 26 39" src="https://user-images.githubusercontent.com/13929023/210167896-34cd5763-1acd-47cd-be90-beac0479aa7d.png">

Proposed solution: 
- Create new hook, `useErasToTimeleft`, where you can pass a `number` of eras into the hook and get the corresponding duration in seconds back.
-  `library/Hooks/useTimeLeft.tsx`: Evolve `timeleftAsString(): string` to `timeLeftAsString(to?: Date):string`. Handle the current era (`toRef.current`) if no `to` is provided as an argument.

Use the 2 above to derive sth. like:

```
...
const { fromNow, timeLeftAsString } = useTimeLeft();
const durationSeconds = useErasToTimeleft(bondDuration);
const durationFormatted = timeLeftAsString(fromNow(durationSeconds));
```

Note: There may be an opportunity to deprecate `useEraTimeLeft` in favour of this new `useErasToTimeLeft` hook after this is implemented.

**Comment by TingALin** [comment]
And have an option to either do “full” format (hours, minutes) or not (hrs, mins). Full can be a Boolean argument that defaults to false

**Comment by TingALin** [comment]
Get rid of “0 hours” /“0 minutes”if hrs/mins is zero
