### ISSUE TITLE
Introduce URL vars: l (language) and n (network)

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#531]
Introduce 2 url variables to load a default locale and a default network upon the first page visit. These url vars can simply be called `l` and `n`, and contain the locale code (`en`, `cn`) and network (`polkadot`, `kusama`, `westend`) respectively.

`localStorage` already stores `network` and `lng`, and these are already loaded as the default setting if they exist. These new url variables should **override** localStorage values - e.g:

 ```
url_var_exists 
   ? url_var 
      : localStorage_exists
          ? local_var 
           : fallback;
```

### Notes

- The `w3f-deploy` branch already has a function in `src/Utils` to get a URL variable. This can now be added to the main codebase:
```
// extracts a URL value from a URL string
export const extractUrlValue = (key: string, url: string) => {
  if (typeof url === 'undefined') url = window.location.href;
  const match = url.match(`[?&]${key}=([^&]+)`);
  return match ? match[1] : null;
};
```

- Since we need to get and use these variables **outside** the react router context, we can simply use [`window`](https://css-tricks.com/snippets/javascript/get-url-and-url-parts-in-javascript/)  to get the URI, and then pass that into `extractUrlValue`. These values only need to be fetched once on the initial page load. 

- New favicons for Kusama and Westend can be generated at https://realfavicongenerator.net/.

**Comment by TingALin** [comment]
The favicon needs to be updated when you switch network
