### ISSUE TITLE
Failed transaction drilldown

### ISSUE THREAD

**Issue by gilescope** [paritytech/polkadot-staking-dashboard#580]
Sometimes it lets me add to a pool that I have already added to, most of the times it doesn't and it says failed transaction, but that toaster popup when I click on it doesn't take me to more information about why the transaction failed. Opening polkadot-js for the block/transaction which failed in a new tab would be really helpful (or some other mechanism to understand why the transaction failed).

**Comment by gilescope** [comment]
(I understand why the transaction failed - non-vested dot can't be used in a staking pool, but I still think linking to the block extrinsic would be really helpful for people to dig into errors)

**Comment by rossbulat** [comment]
Hi @gilescope, apologies for experiencing this issue. It was fixed a while ago but the release is still pending deployment. Hopefully we will see some movement this week.

A part of why the balance chart was redesigned into a multi-bar form factor was also to visualise locked funds easier if they exist in the account. We've thought quite hard on how to elegantly display all the balance variations.

**Comment by gilescope** [comment]
Excellent news. Not being able to see the current account’s balance was my
only other gripe. With these changes it’s going to be pretty slick!
