### ISSUE TITLE
The sender does have enough DOT to submit this transaction.

### ISSUE THREAD

**Issue by Pariz19** [paritytech/polkadot-staking-dashboard#627]
When i try to withdraw mi dot from: https://staking.polkadot.network it says me these text and i cant do anything.

**"Withdrawing rewards will immediately transfer them to your account as free balance.

Estimated Tx Fee: 0.0122512709 DOT

The sender does have enough DOT to submit this transaction."**

**Comment by rossbulat** [comment]
You do not have enough DOT to pay for transaction fees. Deposit a little bit of DOT in your stash and controller account (or just your account if they are the same) to ensure you can pay for transactions.
