### ISSUE TITLE
Staking interface

### ISSUE THREAD

**Issue by AlexUrwald** [paritytech/polkadot-staking-dashboard#653]
Polkadot Staking Dashboard is a great tool to monitor staking on Kusama/Polkadot.
Unfortunately, similar tool doesn't exist for all parachain ecosystem. 

For now, each user have to monitor EACH parachain staking interface and assure to maintain min bound.
This is time consuming and not user friendly

As an example, I had to:
- Claim 25 time on Astar
- Switch 3 time on different validator for moonbeam
- Switch 2 time on different validator for KILT
- Use polkadot js interface at command level to configure Turing staking
...

I am not sure this issue/limitation is correctly understood. It seems, all polkadot developers consider it is normal for a user to take 1 hour every day to monitor by hand each parachain staking mechanism ...

With already 35 parachains running on Polkadot and 43 parachains running on Kusama, how to achieve decentralization and ecosystem mass adoption at parachain level with 50 different interface.

**Comment by rossbulat** [comment]
This is indeed a problem that needs to be solved, but it will not be solved completely within the staking dashboard product. This will involve creating a completely new user experience that is designed from the ground up to handle multi-chain interactions. This is something I am actively researching.
