### ISSUE TITLE
Add support for multiple and custom RPC providers

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot-staking-dashboard#726]
As front-end staking app, it would be valuable to be able to select different RPC providers and not just 1 for each network as defined in [src/config/networks.ts#L17](https://github.com/paritytech/polkadot-staking-dashboard/blob/master/src/config/networks.ts#L17).

Similarly to polkadot.js apps, the app would offer a choice of default providers:

![Screenshot from 2023-03-06 16-05-01](https://user-images.githubusercontent.com/513471/223150758-fec23ad1-1a4a-4d78-9955-6f18e1505a6d.png)

As well as an input box for setting custom RPC URLs which can make it easy to switch to a local or personally trusted node:

![image](https://user-images.githubusercontent.com/513471/223387607-f89c2366-6cb4-4b66-82c2-812c147f93f8.png)

Moreover, the great [URL variable support](https://github.com/paritytech/polkadot-staking-dashboard#url-variables-support) can keep this value in memory, allowing easy bookmarking of preferred RPC provider.

**Comment by phillux** [comment]
I would also really like the option of choosing a local node.

**Comment by PierreBesson** [comment]
Reopening as I think it was closed unintentionally.

**Comment by PierreBesson** [comment]
Reopening as it looks like it is not yet supported.
