### ISSUE TITLE
Hide the inactive components in nomination pool page.

### ISSUE THREAD

**Issue by hamidra** [paritytech/polkadot-staking-dashboard#80]
When an account is not participating in nomination pools, hide the components that are inactive for a user in that state.

![Screen Shot 2022-05-31 at 7 30 23 AM](https://user-images.githubusercontent.com/5099795/171198712-79214956-2665-49b9-adf1-78356bca4809.png)

**Comment by rossbulat** [comment]
I think these components should stay where they are to keep consistency between Stake and Pools pages, and to not surprise the user when they start to stake - they will already know where all the toggles are.

I do believe that the Pools list is a bit out of place. Just like the validator list is separate from the Stake page, it would be nice to find a good way to separate the pools list from the pools page. 

Perhaps have tabs below the page title (these will need to be integrated in the PageTitle component so they become sticky when scrolling down) and have an "Overview" and "Pools" tab to switch between.

In addition, have an extra button next to Create Pool, Join Pool, that switches to the Pools tab. These buttons could also be accompanied with an icon and made bigger to fall inline with the Start Staking button on the Stake page.

This is probs the direction I'd go in!
