### ISSUE TITLE
(i) should act as toggle

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot-staking-dashboard#87]
Really small/nit like feature request. When you press the ℹ️ button a tooltip with helpful information pops up. 

<img width="222" alt="Screenshot 2022-06-01 at 20 21 14" src="https://user-images.githubusercontent.com/2205845/171475249-406eb13f-cb81-4b0c-8fba-20e4e6eb052c.png">

When I finish reading the tooltip and don't need it I expect that it would be possible to close the tooltip with another click on the ℹ️ button. In other words, I expect the button to act as a toggle. 

It would really good if the ℹ️ button acted as a toggle. If that was the case, I would not have to move my cursor to close the tooltip.

**Comment by rossbulat** [comment]
Good catch @pepyakin! I've now enabled that.
