### ISSUE TITLE
Back Button Hijacked

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-staking-dashboard#900]
Hello, really sleek-looking site! Minor UX issue:

I navigated to https://staking.polkadot.network/ from ~Google~ Kagi on Firefox and noticed that I wasn't able to go back. I just kept getting redirected to the https://staking.polkadot.network/#/overview page.

**Comment by mrcnski** [comment]
Interesting! Thanks for looking into it, feel free to close if not actionable.

**Comment by rossbulat** [comment]
Thank you, I will close for now.
