### ISSUE TITLE
Adding a Controller account still leaves the pop-up (add controller) showing

### ISSUE THREAD

**Issue by wirednkod** [paritytech/polkadot-staking-dashboard#916]
When adding a new staking account (stash) and the full process is finished, there appears a "notification" asking to add a controller account for that stash;
Once this process is completed - even though the controller is added successfully, the notification remains there (see screenshot below)

![image](https://user-images.githubusercontent.com/5408605/232751643-1a4b1506-617b-463c-8e49-959d33371926.png)

**Comment by rossbulat** [comment]
Thanks for reporting. This is slightly annoying - it needs to be fixed but at the same time we really want to move away from the controller and to proxies. I think it is worth investigating a quick fix for the next release.

**Comment by wirednkod** [comment]
Adding some extra detail- IMO - the notification should disappear as soon as the controller account is added (there should be no need of refresh)

**Comment by rossbulat** [comment]
Yes. That is the behaviour that should be there.

**Comment by rossbulat** [comment]
Fixed in #942.
