### ISSUE TITLE
Fast Unstake: Not enough DOT to sign transaction

### ISSUE THREAD

**Issue by wirednkod** [paritytech/polkadot-staking-dashboard#918]
When trying to fast unstake - initially my account does not have enough DOT;
I sent extra DOT for signing to my account, and refreshed the page, but even thought the DOT were there, I was not able to fast unstake as it was mentioned that I do not have enough DOT for signing the action

**Comment by rossbulat** [comment]
Is there enough DOT to cover the deposit? I believe it is 1 DOT.

**Comment by rossbulat** [comment]
I suspect this might be a balance calculation issue. I have addressed an issue where the dashboard was reserving free balance even when account locks were in place - this may have a positive impact on this issue. 
I think it is wise to revisit this after #861 is addressed, once `system.accounts` changes in next runtime upgrade are reflected in the `Balances` context, so we do not have to solve the same problem twice.

**Comment by wirednkod** [comment]
Thank you @rossbulat 
Ill close it for now and will reopen if appears
