### ISSUE TITLE
Rename SectionWrapper to CardWrapper

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#92]
We want to normalise naming conventions, and one of those strange names that have maintained is "SectionWrapper". A section is clearly just a card, so we want to move away from "Section" and just have "Card".

This mainly effects the `SectionWrapper` component, but there are some other wrappers that adopt the same name that can be changed.

**Comment by TingALin** [comment]
can you assign me to this issue?
