### ISSUE TITLE
Add all Nomination Pool Extrinsics

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-staking-dashboard#93]
Extrinsics to complete for nomination pools to feature completeness:
- [x] Withdraw 
- [x] Leave pool

And for role specific:
- [x] Destroying a pool (root - does the depositor have a play here?)
- [x] Nominate (nominator)
- [x] State toggling (state toggler)
- [x] Stop nominating nominations
- [x] Assigning accounts to roles (updating roles)

**Comment by hamidra** [comment]
claim, unbond, withdraw and leave added by #95

**Comment by hamidra** [comment]
closed by #36 for the final remaining item.
