### ISSUE TITLE
Talisman seems as not connected

### ISSUE THREAD

**Issue by wirednkod** [paritytech/polkadot-staking-dashboard#951]
on the https://paritytech.github.io/polkadot-staking-dashboard/ I am trying to connect Talisman (extension is installed and unlocked), and when Clicking on Connect - I receive a notification that "The Talisman extension has been connected."; 
Going to accounts though it shows that there are no active `Accounts`; Also the `Connect +` remains as not connected

It seems that to "overcome" that UI/UX "issue" - one needs to connect accounts from talisman extension and then refresh the page to see that the Extensionis connected
 

![image](https://user-images.githubusercontent.com/5408605/234561030-ad24ff34-0011-4e14-9702-278d37c14c8d.png)

**Comment by rossbulat** [comment]
Thanks for reporting! Fixed in #999.
