### ISSUE TITLE
Ensure metadata batchKeys are unique

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#99]
Every `<ValidatorList />`, and a couple of other components, reference their own "meta batch": a bunch of subscriptions that maintain data for that list or component in question. Each meta batch is isolated, and as such have unique keys to access them.

If you global search `const batchKey` you will find various strings defined (that should all be unique), for example:
```
const batchKey = 'favourite_validators';
```

The issue is we are not currently programatically ensuring these batch keys are unique.

Proposed solution:
   - Have a global static class that keeps track of the keys in an array.
   - Have a method that is called when creating a new batchKey, returning the string and using `console.error` if that key has already been defined.

Utilising this class, the new code will look something like this:
```
const batchKey = BatchKeys.new('favourite_validators');
```

As additional background, I recently added [a webpack config](https://github.com/paritytech/polkadot-staking-dashboard/pull/100/commits/4004ff9a50077bb34c3fd31b41a40adaad93cf24) via [`terser-webpack-plugin`](terser-webpack-plugin) to remove console statements from the production build.

**Comment by TingALin** [comment]
I can work on this

**Comment by rossbulat** [comment]
@TingALin great. Let's get a draft submitted when you're ready and explore if we can further improve the solution.
